name: CI Pre-Build with Gradle

on:
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    name: Unit-testing with Gradle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Execute tests
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: test
  code-analysis:
    name: Code-analysis with SonarQube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Analyis code
        uses: eskatos/gradle-command-action@v1
        env:
          URL: ${{ secrets.SONARQUBE_HOST }}
          TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        with:
          arguments: sonarqube
            -Dsonar.host.url=${{ env.URL }}
            -Dsonar.login=${{ env.TOKEN }}
